steps:
  - name: 'Checkout'
    uses: 'actions/checkout@v3'

  - name: 'Google auth'
    id: 'auth'
    uses: 'google-github-actions/auth@v1'
    with:
      workload_identity_provider: 'projects/818379691618/locations/global/workloadIdentityPools/aura-dev-github-actions-id-pool/providers/aura-github-dev-provider'
      service_account: 'aura-dev-github-actions@symbolic-fire-321702.iam.gserviceaccount.com'

  - name: 'Set up Cloud SDK'
    uses: 'google-github-actions/setup-gcloud@v1'
    with:
      project_id: '${{ env.PROJECT_ID }}'
