name: Aurabox deploy

on: [pull_request, push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/818379691618/locations/global/workloadIdentityPools/aura-dev-github-actions-id-pool/providers/aura-github-dev-provider'
          service_account: 'aura-dev-github-actions@symbolic-fire-321702.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: 'symbolic-fire-321702'

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies 📦
        run: yarn install

      - name: Build 🏗️
        run: yarn install

      - name: Move envs
        run: |
          mv platform/app/.env platform/app/.env.mainline
          mv platform/app/.env.aura platform/app/.env

      - name: Show
        run: ls -la platform/viewer/dist

#      - name: 'Push to storage'
#        uses: 'google-github-actions/upload-cloud-storage@v1'
#        with:
#          path: '/path/to/file'
#          destination: 'bucket-name/file'
